version: 0.2

phases:
  build:
    commands:
      - CurrentVersion=$(echo $(aws lambda get-alias --function-name yoppy-test2 --name CDVersion | grep FunctionVersion | tail -1 |tr -cd "[0-9]"))
  post_build:
    commands:
      - ls
      - aws lambda publish-version --function-name yoppy-test2
      - TargetVersion=$(echo $(aws lambda list-versions-by-function --function-name yoppy-test2 | grep Version | tail -1 | tr -cd "[0-9]"))
      - echo $CurrentVersion
      - echo $TargetVersion


artifacts:
  type: zip
  files:
    - appspec.yaml
    - lambda_function.py

